// Games by Hyper 2026.
// Generated by Tools/Catalog/build_catalog.py; do not hand-edit.

#pragma once

#include "CoreMinimal.h"

/** Sizes of the generated capability catalog. Code and tests use these instead of literal counts. */
namespace HyperAIStudio::CapabilityCatalog
{
	constexpr int32 GeneratedToolCount = 115;
	constexpr int32 GeneratedPackCount = 28;
	constexpr int32 GeneratedSourceArtifactCount = 115;
}
