#!/usr/bin/env python3
# Games by Hyper 2026.
"""Builds HyperAIStudioCapabilityPackCatalog.generated.inl from catalog_source.json.

The source JSON holds only what a person decides. Everything the C++ validator derives or cross-checks
(pack tool lists, cohorts, admission, external effects, ledger coverage, artifact totals) is derived here,
so it cannot drift. The fingerprint mirrors BuildCatalogFingerprint in HyperAIStudioCapabilityPackRegistry.cpp.

  python build_catalog.py seed    # one-off: current .inl -> catalog_source.json
  python build_catalog.py build   # catalog_source.json -> .inl + counts header
  python build_catalog.py check   # fail if generated files are stale or tool names drifted from source
"""
import glob
import hashlib
import json
import os
import re
import sys
from collections import OrderedDict

HERE = os.path.dirname(os.path.abspath(__file__))
PLUGIN = os.path.normpath(os.path.join(HERE, "..", ".."))
SOURCE_JSON = os.path.join(HERE, "catalog_source.json")
INL = os.path.join(PLUGIN, "Source", "HyperAIStudio", "Private", "HyperAIStudioCapabilityPackCatalog.generated.inl")
COUNTS_H = os.path.join(PLUGIN, "Source", "HyperAIStudio", "Public", "HyperAIStudioCapabilityCatalogCounts.h")
GENERATOR_LINE = "// Generated by Tools/Catalog/build_catalog.py; do not hand-edit."

PREREQ_KINDS = ["Plugin", "Module", "Probe"]
TIERS = ["Core", "Optional"]
ADMISSION = ["Planned", "SourceCandidate", "Admitted"]
MODES = ["AllOf", "AnyOf"]
COVERAGE = ["MappedSourceRows", "ApprovedPlanExtension"]
SAFETY = ["Read", "Edit", "Destructive", "ExternalEffect"]
EMPTY_LEDGER = "sha256:" + hashlib.sha256(b"[]").hexdigest()
SHA256_RE = re.compile(r"^sha256:[0-9a-f]{64}$")


def sha256(text):
    return "sha256:" + hashlib.sha256(text.encode("utf-8")).hexdigest()


# ---------------------------------------------------------------- fingerprint (mirrors the C++ exactly)

def tok(value):
    return "%d:%s|" % (len(value.encode("utf-8")), value)


def tok_int(value):
    return tok("%d" % value)


def tok_bool(value):
    return tok("1" if value else "0")


def tok_seq(values):
    # FString::Compare(CaseSensitive) is ordinal on UTF-16 units; every id here is ASCII, so sorted() agrees.
    values = sorted(values)
    return tok_int(len(values)) + "".join(tok(v) for v in values)


def fingerprint(cat):
    out = tok("hyperai.capability-pack-catalog.semantic.v2")
    for key in ("Schema", "ApprovedPlanFingerprint", "AdmissionMatrixFingerprint",
                "SourceLedgerFingerprint", "SourceArtifactFingerprint"):
        out += tok(cat[key])
    out += tok_int(cat["SourceArtifactCount"])
    out += tok_seq([tok("prerequisite") + tok(p["Id"]) + tok_int(PREREQ_KINDS.index(p["Kind"]))
                    for p in cat["Prerequisites"]])
    pack_rows = []
    for p in cat["Packs"]:
        req_rows = [tok("requirement") + tok(g["Id"]) + tok_int(MODES.index(g["Mode"])) + tok_bool(g["bBlocking"])
                    + tok_seq(g["PrerequisiteIds"]) for g in p["Requirements"]]
        pack_rows.append(tok("pack") + tok(p["Id"]) + tok_int(TIERS.index(p["Tier"]))
                         + tok_int(ADMISSION.index(p["AdmissionState"])) + tok_bool(p["bContainsExternalEffects"])
                         + tok_seq(p["DependsOnPackIds"]) + tok_seq(p["AtomicCohortIds"]) + tok_seq(p["ToolNames"])
                         + tok_seq(req_rows))
    out += tok_seq(pack_rows)
    tool_rows = []
    for t in cat["Tools"]:
        tool_rows.append(tok("tool") + tok(t["Name"]) + tok(t["PackId"]) + tok(t["AtomicCohortId"])
                         + tok_seq(t["RequiredNonBlockingRequirementGroupIds"])
                         + tok_seq(["%u" % SAFETY.index(s) for s in t["AllowedSafetyClasses"]])
                         + tok_int(ADMISSION.index(t["AdmissionState"])) + tok_bool(t["bMayCauseExternalEffects"])
                         + tok_int(t["SourceArtifactCount"]) + tok(t["SourceArtifactFingerprint"])
                         + tok_int(t["SourceLedgerRowCount"]) + tok(t["SourceLedgerFingerprint"])
                         + tok_int(COVERAGE.index(t["SourceLedgerCoverage"])) + tok_int(t["PlatformEvidenceRows"])
                         + tok_int(t["ProductEvidenceRows"]) + tok_int(t["SupplementalEvidenceRows"]))
    out += tok_seq(tool_rows)
    return sha256(out)


# ---------------------------------------------------------------- .inl parsing (seed only)

def _decode(raw):
    raw = raw.strip()
    m = re.fullmatch(r'TEXT\("([^"]*)"\)', raw)
    if m:
        return m.group(1)
    if raw in ("true", "false"):
        return raw == "true"
    if re.fullmatch(r"-?\d+", raw):
        return int(raw)
    m = re.fullmatch(r"\w+::(\w+)", raw)
    if m:
        return m.group(1)
    raise ValueError("unparsed value: " + raw)


def parse_inl(text):
    cat = {"Prerequisites": [], "Packs": [], "Tools": []}
    cur = group = None
    for line in text.split("\r\n"):
        s = line.strip()
        m = re.fullmatch(r"OutCatalog\.(\w+) = (.+);", s)
        if m:
            cat[m.group(1)] = _decode(m.group(2))
            continue
        if s.startswith("FHyperAIStudioCapabilityPrerequisiteDefinition&"):
            cur = {}
            cat["Prerequisites"].append(cur)
        elif s.startswith("FHyperAIStudioCapabilityPackDefinition&"):
            cur = {"DependsOnPackIds": [], "AtomicCohortIds": [], "ToolNames": [], "Requirements": []}
            cat["Packs"].append(cur)
        elif s.startswith("FHyperAIStudioCapabilityRequirementGroup&"):
            group = {"PrerequisiteIds": []}
            cur["Requirements"].append(group)
        elif s.startswith("FHyperAIStudioCapabilityToolDefinition&"):
            cur = {"RequiredNonBlockingRequirementGroupIds": [], "AllowedSafetyClasses": []}
            cat["Tools"].append(cur)
        else:
            m = re.fullmatch(r"(Item|Pack|Group|Tool)\.(\w+)(?:\.Add\((.+)\)| = (.+));", s)
            if not m:
                continue
            target = group if m.group(1) == "Group" else cur
            if m.group(3) is not None:
                target[m.group(2)].append(_decode(m.group(3)))
            else:
                target[m.group(2)] = _decode(m.group(4))
    return cat


def to_source(cat):
    """Full catalog -> source JSON, dropping derived fields after proving they really are derivable."""
    tools_by_name = {t["Name"]: t for t in cat["Tools"]}
    src = OrderedDict()
    src["schema"] = cat["Schema"]
    src["approvedPlanFingerprint"] = cat["ApprovedPlanFingerprint"]
    src["admissionMatrixFingerprint"] = cat["AdmissionMatrixFingerprint"]
    src["sourceLedgerFingerprint"] = cat["SourceLedgerFingerprint"]
    src["sourceArtifactFingerprint"] = cat["SourceArtifactFingerprint"]
    src["prerequisites"] = [OrderedDict([("id", p["Id"]), ("kind", p["Kind"])]) for p in cat["Prerequisites"]]
    src["packs"] = []
    for p in cat["Packs"]:
        sp = OrderedDict([("id", p["Id"]), ("tier", p["Tier"]), ("dependsOn", p["DependsOnPackIds"])])
        sp["requirements"] = [OrderedDict([("id", g["Id"]), ("mode", g["Mode"]), ("blocking", g["bBlocking"]),
                                           ("prerequisites", g["PrerequisiteIds"])]) for g in p["Requirements"]]
        sp["tools"] = []
        for name in p["ToolNames"]:
            t = tools_by_name[name]
            st = OrderedDict([("name", name), ("cohort", t["AtomicCohortId"]), ("admission", t["AdmissionState"]),
                              ("safety", t["AllowedSafetyClasses"])])
            if t["RequiredNonBlockingRequirementGroupIds"]:
                st["nonBlockingGroups"] = t["RequiredNonBlockingRequirementGroupIds"]
            st["sourceArtifactCount"] = t["SourceArtifactCount"]
            st["sourceArtifactFingerprint"] = t["SourceArtifactFingerprint"]
            st["ledgerFingerprint"] = t["SourceLedgerFingerprint"]
            st["evidence"] = [t["PlatformEvidenceRows"], t["ProductEvidenceRows"], t["SupplementalEvidenceRows"]]
            sp["tools"].append(st)
        cohorts = list(OrderedDict.fromkeys(t["cohort"] for t in sp["tools"]))
        if cohorts != p["AtomicCohortIds"]:
            sp["cohortOrder"] = p["AtomicCohortIds"]  # only kept when first-appearance order does not reproduce it
        src["packs"].append(sp)
    return src


# ---------------------------------------------------------------- source JSON -> full catalog

def expand(src):
    cat = {"Schema": src["schema"], "ApprovedPlanFingerprint": src["approvedPlanFingerprint"],
           "AdmissionMatrixFingerprint": src["admissionMatrixFingerprint"],
           "SourceLedgerFingerprint": src["sourceLedgerFingerprint"],
           "SourceArtifactFingerprint": src["sourceArtifactFingerprint"],
           "Prerequisites": sorted(({"Id": p["id"], "Kind": p["kind"]} for p in src["prerequisites"]),
                                   key=lambda p: p["Id"]),
           "Packs": [], "Tools": []}
    for sp in src["packs"]:
        tools = []
        for st in sp["tools"]:
            evidence = st.get("evidence", [0, 0, 0])
            rows = sum(evidence)
            tools.append({
                "Name": st["name"], "PackId": sp["id"], "AtomicCohortId": st["cohort"],
                "AdmissionState": st.get("admission", "SourceCandidate"),
                "bMayCauseExternalEffects": "ExternalEffect" in st["safety"],
                "SourceArtifactCount": st.get("sourceArtifactCount", 1),
                "SourceArtifactFingerprint": st.get("sourceArtifactFingerprint") or sha256(
                    "hyperai.tool-artifact.v1|%s|%s|%s" % (sp["id"], st["cohort"], st["name"])),
                "SourceLedgerRowCount": rows,
                "SourceLedgerFingerprint": st.get("ledgerFingerprint", EMPTY_LEDGER),
                "SourceLedgerCoverage": "MappedSourceRows" if rows > 0 else "ApprovedPlanExtension",
                "PlatformEvidenceRows": evidence[0], "ProductEvidenceRows": evidence[1],
                "SupplementalEvidenceRows": evidence[2],
                "RequiredNonBlockingRequirementGroupIds": list(st.get("nonBlockingGroups", [])),
                "AllowedSafetyClasses": list(st["safety"]),
            })
        states = {t["AdmissionState"] for t in tools}
        admission = "Planned" if "Planned" in states else ("SourceCandidate" if "SourceCandidate" in states else "Admitted")
        cat["Packs"].append({
            "Id": sp["id"], "Tier": sp["tier"], "AdmissionState": admission,
            "bContainsExternalEffects": any(t["bMayCauseExternalEffects"] for t in tools),
            "DependsOnPackIds": list(sp.get("dependsOn", [])),
            "AtomicCohortIds": list(sp.get("cohortOrder") or OrderedDict.fromkeys(t["AtomicCohortId"] for t in tools)),
            "ToolNames": [t["Name"] for t in tools],
            "Requirements": [{"Id": g["id"], "Mode": g["mode"], "bBlocking": g["blocking"],
                              "PrerequisiteIds": list(g["prerequisites"])} for g in sp.get("requirements", [])],
        })
        cat["Tools"].extend(tools)
    cat["SourceArtifactCount"] = sum(t["SourceArtifactCount"] for t in cat["Tools"])
    cat["GeneratedFingerprint"] = fingerprint(cat)
    return cat


def validate(cat):
    """The rules ValidateCatalog enforces that derivation alone does not guarantee."""
    errors = []
    prereqs = [p["Id"] for p in cat["Prerequisites"]]
    if len(set(prereqs)) != len(prereqs):
        errors.append("duplicate prerequisite id")
    for p in cat["Prerequisites"]:
        if p["Kind"] not in PREREQ_KINDS:
            errors.append("prerequisite %s: bad kind %s" % (p["Id"], p["Kind"]))
    for key in ("ApprovedPlanFingerprint", "AdmissionMatrixFingerprint", "SourceLedgerFingerprint",
                "SourceArtifactFingerprint"):
        if not SHA256_RE.match(cat[key]):
            errors.append("catalog %s is not sha256:<64 hex>" % key)
    pack_ids = [p["Id"] for p in cat["Packs"]]
    if len(set(pack_ids)) != len(pack_ids):
        errors.append("duplicate pack id")
    packs = {p["Id"]: p for p in cat["Packs"]}
    for p in cat["Packs"]:
        if p["Tier"] not in TIERS:
            errors.append("pack %s: bad tier" % p["Id"])
        if not p["ToolNames"]:
            errors.append("pack %s has no tools" % p["Id"])
        for dep in p["DependsOnPackIds"]:
            if dep not in packs:
                errors.append("pack %s depends on unknown pack %s" % (p["Id"], dep))
        group_ids = [g["Id"] for g in p["Requirements"]]
        if len(set(group_ids)) != len(group_ids) or "" in group_ids:
            errors.append("pack %s: duplicate or empty requirement id" % p["Id"])
        for g in p["Requirements"]:
            if g["Mode"] not in MODES:
                errors.append("pack %s group %s: bad mode" % (p["Id"], g["Id"]))
            if not g["PrerequisiteIds"] or len(set(g["PrerequisiteIds"])) != len(g["PrerequisiteIds"]):
                errors.append("pack %s group %s: empty or duplicate prerequisites" % (p["Id"], g["Id"]))
            for pre in g["PrerequisiteIds"]:
                if pre not in prereqs:
                    errors.append("pack %s group %s: unknown prerequisite %s" % (p["Id"], g["Id"], pre))
    visiting, visited = set(), set()

    def visit(pid):
        if pid in visiting:
            errors.append("pack dependency cycle through %s" % pid)
            return
        if pid in visited or pid not in packs:
            return
        visiting.add(pid)
        for dep in packs[pid]["DependsOnPackIds"]:
            visit(dep)
        visiting.discard(pid)
        visited.add(pid)

    for pid in sorted(packs):
        visit(pid)
    names = [t["Name"] for t in cat["Tools"]]
    if len(set(names)) != len(names) or "" in names:
        errors.append("duplicate or empty tool name")
    cohort_states, cohort_groups = {}, {}
    for t in cat["Tools"]:
        if not t["AtomicCohortId"]:
            errors.append("tool %s: missing cohort" % t["Name"])
        if t["AdmissionState"] not in ADMISSION:
            errors.append("tool %s: bad admission" % t["Name"])
        if not t["AllowedSafetyClasses"] or len(set(t["AllowedSafetyClasses"])) != len(t["AllowedSafetyClasses"]):
            errors.append("tool %s: empty or duplicate safety classes" % t["Name"])
        for s in t["AllowedSafetyClasses"]:
            if s not in SAFETY:
                errors.append("tool %s: bad safety class %s" % (t["Name"], s))
        if t["SourceArtifactCount"] <= 0:  # the runtime index also needs > 0
            errors.append("tool %s: SourceArtifactCount must be > 0" % t["Name"])
        for key in ("SourceArtifactFingerprint", "SourceLedgerFingerprint"):
            if not SHA256_RE.match(t[key]):
                errors.append("tool %s: %s is not sha256:<64 hex>" % (t["Name"], key))
        groups = sorted(t["RequiredNonBlockingRequirementGroupIds"])
        if len(set(groups)) != len(groups):
            errors.append("tool %s: duplicate non-blocking group" % t["Name"])
        pack_groups = {g["Id"]: g for g in packs[t["PackId"]]["Requirements"]}
        for gid in groups:
            if gid not in pack_groups or pack_groups[gid]["bBlocking"]:
                errors.append("tool %s: %s is not a non-blocking group of its pack" % (t["Name"], gid))
        cohort_states.setdefault(t["AtomicCohortId"], set()).add(t["AdmissionState"])
        if cohort_groups.setdefault(t["AtomicCohortId"], groups) != groups:
            errors.append("cohort %s: tools disagree on non-blocking groups" % t["AtomicCohortId"])
    for cohort, states in cohort_states.items():
        if len(states) != 1:
            errors.append("cohort %s: mixed admission states" % cohort)
    return errors


# ---------------------------------------------------------------- emit

def emit_inl(cat):
    L = ["// Games by Hyper 2026.", GENERATOR_LINE, "",
         "static void PopulateGeneratedCapabilityPackCatalog(FHyperAIStudioCapabilityCatalog& OutCatalog)", "{"]
    for key in ("Schema", "GeneratedFingerprint", "ApprovedPlanFingerprint", "AdmissionMatrixFingerprint",
                "SourceLedgerFingerprint", "SourceArtifactFingerprint"):
        L.append('\tOutCatalog.%s = TEXT("%s");' % (key, cat[key]))
    L += ["\tOutCatalog.SourceArtifactCount = %d;" % cat["SourceArtifactCount"], ""]
    b = lambda v: "true" if v else "false"
    for p in cat["Prerequisites"]:
        L += ["\t{", "\t\tFHyperAIStudioCapabilityPrerequisiteDefinition& Item = OutCatalog.Prerequisites.AddDefaulted_GetRef();",
              '\t\tItem.Id = TEXT("%s");' % p["Id"],
              "\t\tItem.Kind = EHyperAIStudioCapabilityPrerequisiteKind::%s;" % p["Kind"], "\t}"]
    L.append("")
    for p in cat["Packs"]:
        L += ["\t{", "\t\tFHyperAIStudioCapabilityPackDefinition& Pack = OutCatalog.Packs.AddDefaulted_GetRef();",
              '\t\tPack.Id = TEXT("%s");' % p["Id"],
              "\t\tPack.Tier = EHyperAIStudioCapabilityPackTier::%s;" % p["Tier"],
              "\t\tPack.AdmissionState = EHyperAIStudioCapabilityAdmissionState::%s;" % p["AdmissionState"],
              "\t\tPack.bContainsExternalEffects = %s;" % b(p["bContainsExternalEffects"])]
        L += ['\t\tPack.DependsOnPackIds.Add(TEXT("%s"));' % v for v in p["DependsOnPackIds"]]
        L += ['\t\tPack.AtomicCohortIds.Add(TEXT("%s"));' % v for v in p["AtomicCohortIds"]]
        L += ['\t\tPack.ToolNames.Add(TEXT("%s"));' % v for v in p["ToolNames"]]
        for g in p["Requirements"]:
            L += ["\t\t{", "\t\t\tFHyperAIStudioCapabilityRequirementGroup& Group = Pack.Requirements.AddDefaulted_GetRef();",
                  '\t\t\tGroup.Id = TEXT("%s");' % g["Id"],
                  "\t\t\tGroup.Mode = EHyperAIStudioCapabilityRequirementMode::%s;" % g["Mode"],
                  "\t\t\tGroup.bBlocking = %s;" % b(g["bBlocking"])]
            L += ['\t\t\tGroup.PrerequisiteIds.Add(TEXT("%s"));' % v for v in g["PrerequisiteIds"]]
            L.append("\t\t}")
        L.append("\t}")
    L.append("")
    for t in cat["Tools"]:
        L += ["\t{", "\t\tFHyperAIStudioCapabilityToolDefinition& Tool = OutCatalog.Tools.AddDefaulted_GetRef();",
              '\t\tTool.Name = TEXT("%s");' % t["Name"], '\t\tTool.PackId = TEXT("%s");' % t["PackId"],
              '\t\tTool.AtomicCohortId = TEXT("%s");' % t["AtomicCohortId"],
              "\t\tTool.AdmissionState = EHyperAIStudioCapabilityAdmissionState::%s;" % t["AdmissionState"],
              "\t\tTool.bMayCauseExternalEffects = %s;" % b(t["bMayCauseExternalEffects"]),
              "\t\tTool.SourceArtifactCount = %d;" % t["SourceArtifactCount"],
              '\t\tTool.SourceArtifactFingerprint = TEXT("%s");' % t["SourceArtifactFingerprint"],
              "\t\tTool.SourceLedgerRowCount = %d;" % t["SourceLedgerRowCount"],
              '\t\tTool.SourceLedgerFingerprint = TEXT("%s");' % t["SourceLedgerFingerprint"],
              "\t\tTool.SourceLedgerCoverage = EHyperAIStudioCapabilityLedgerCoverage::%s;" % t["SourceLedgerCoverage"],
              "\t\tTool.PlatformEvidenceRows = %d;" % t["PlatformEvidenceRows"],
              "\t\tTool.ProductEvidenceRows = %d;" % t["ProductEvidenceRows"],
              "\t\tTool.SupplementalEvidenceRows = %d;" % t["SupplementalEvidenceRows"]]
        L += ['\t\tTool.RequiredNonBlockingRequirementGroupIds.Add(TEXT("%s"));' % v
              for v in t["RequiredNonBlockingRequirementGroupIds"]]
        L += ["\t\tTool.AllowedSafetyClasses.Add(EHyperAIStudioCapabilitySafetyClass::%s);" % v
              for v in t["AllowedSafetyClasses"]]
        L.append("\t}")
    L.append("}")
    return "\r\n".join(L) + "\r\n"


def emit_counts(cat):
    L = ["// Games by Hyper 2026.", GENERATOR_LINE, "", "#pragma once", "", '#include "CoreMinimal.h"', "",
         "/** Sizes of the generated capability catalog. Code and tests use these instead of literal counts. */",
         "namespace HyperAIStudio::CapabilityCatalog", "{",
         "\tconstexpr int32 GeneratedToolCount = %d;" % len(cat["Tools"]),
         "\tconstexpr int32 GeneratedPackCount = %d;" % len(cat["Packs"]),
         "\tconstexpr int32 GeneratedSourceArtifactCount = %d;" % cat["SourceArtifactCount"], "}"]
    return "\r\n".join(L) + "\r\n"


# ---------------------------------------------------------------- tool-name drift across the five hand-written copies

def declared_tool_names():
    """Every `static ... hyper_*(` UFUNCTION declared in a module header (tests excluded)."""
    found = {}
    for header in glob.glob(os.path.join(PLUGIN, "Source", "**", "*.h"), recursive=True):
        rel = os.path.relpath(header, os.path.join(PLUGIN, "Source"))
        if os.sep + "Tests" + os.sep in os.sep + rel:
            continue
        text = open(header, encoding="utf-8", errors="replace").read()
        for m in re.finditer(r"\bstatic\s+[\w:<>\*&, ]+?\s+(hyper_\w+)\s*\(", text):
            found.setdefault(m.group(1), rel.split(os.sep)[0])
    return found


def load_source():
    with open(SOURCE_JSON, encoding="utf-8") as f:
        return json.load(f, object_pairs_hook=OrderedDict)


def read_bytes(path):
    with open(path, "rb") as f:
        return f.read()


def write_crlf(path, text):
    with open(path, "wb") as f:
        f.write(text.encode("utf-8"))


def main(argv):
    command = argv[1] if len(argv) > 1 else "check"
    if command == "seed":
        original = read_bytes(INL).decode("utf-8")
        parsed = parse_inl(original)
        src = to_source(parsed)
        rebuilt = emit_inl(expand(src))
        # Golden gate: the seed is only accepted if it reproduces today's file (bar the generator comment).
        drop = lambda t: t.split("\r\n", 2)[2]
        if drop(rebuilt) != drop(original):
            for i, (a, b) in enumerate(zip(drop(original).split("\r\n"), drop(rebuilt).split("\r\n"))):
                if a != b:
                    print("first difference at body line %d:\n  file:  %r\n  built: %r" % (i + 3, a, b))
                    break
            return 1
        with open(SOURCE_JSON, "w", encoding="utf-8", newline="\n") as f:
            json.dump(src, f, indent=1)
            f.write("\n")
        print("seeded %s from %d packs / %d tools; rebuild reproduces the current catalog"
              % (os.path.relpath(SOURCE_JSON, PLUGIN), len(parsed["Packs"]), len(parsed["Tools"])))
        return 0

    cat = expand(load_source())
    errors = validate(cat)
    declared = declared_tool_names()
    catalog_names = {t["Name"] for t in cat["Tools"]}
    for name in sorted(set(declared) - catalog_names):
        errors.append("%s is declared in Source/%s but missing from catalog_source.json" % (name, declared[name]))
    for name in sorted(catalog_names - set(declared)):
        errors.append("%s is in catalog_source.json but no module declares it" % name)
    if errors:
        print("catalog source is invalid:\n  " + "\n  ".join(errors))
        return 1

    outputs = {INL: emit_inl(cat), COUNTS_H: emit_counts(cat)}
    if command == "build":
        for path, text in outputs.items():
            write_crlf(path, text)
        print("built %d packs / %d tools, fingerprint %s" % (len(cat["Packs"]), len(cat["Tools"]),
                                                            cat["GeneratedFingerprint"]))
        return 0
    if command == "check":
        # Line endings are git's business (autocrlf); only content counts as stale.
        lf = lambda data: data.replace(b"\r\n", b"\n")
        stale = [os.path.relpath(p, PLUGIN) for p, text in outputs.items()
                 if not os.path.exists(p) or lf(read_bytes(p)) != lf(text.encode("utf-8"))]
        if stale:
            print("stale generated files (run build): " + ", ".join(stale))
            return 1
        print("catalog up to date: %d packs / %d tools, %s" % (len(cat["Packs"]), len(cat["Tools"]),
                                                              cat["GeneratedFingerprint"]))
        return 0
    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
